from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from . import views
from .views import *

urlpatterns = [
    path('', views.landing, name='landing'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='accounts/User/reset_password.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/User/reset_password_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/User/reset.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/User/reset_password_complete.html'), name='password_reset_complete'),
    path('purchaseorder/', views.purchaseorder, name='purchaseorder'),
    path('main/', views.main, name='main'),
    path('bac/', views.bac, name='bac'),
    path('baclanding/', views.baclanding, name='baclanding'),
    path('userlanding/', views.userlanding, name='userlanding'),
    path('ppmp101/', views.ppmp101, name='ppmp101'),
    path('ppmp2/', views.ppmp2, name='ppmp2'),
    path('login/', views.login, name='login'),
    path('item/<int:pk>/list/', views.item_list, name='item_list'),
    path('register/', views.register, name='register'),
    path('requests/', views.requests, name='requests'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('catalogue/', views.catalogue, name='catalogue'),
    path('tracker/', views.tracker, name='tracker'),
    path('about/', views.about, name='about'),
    path('bac_prof/', views.bac_prof, name='bac_prof'),
    path('bac_profile/', views.bac_profile, name='bac_profile'),
    path('profile/', views.profile, name='profile'),
    path('bac_about/', views.bac_about, name='bac_about'),
    path('bac_home/', views.bac_home, name='bac_home'),
    path('prof/', views.prof, name='prof'),
    path('preqform/<str:pr_id>/', views.preqform, name='preqform'),
    path('np/', views.np, name='np'),
    path('bids/', views.bids, name='bids'),
    path('noa/', views.noa, name='noa'),
    path('notif/', views.notif, name='notif'),
    path('inspection/', views.inspection, name='inspection'),
    path('purchaseorder/', views.purchaseorder, name='purchaseorder'),
    path('property/', views.property, name='property'),
    path('abstract/', views.abstract, name='abstract'),
    path('bo/', views.bo, name='bo'),
    path('boabout/', views.boabout, name='boabout'),
    path('cd/', views.cd, name='cd'),
    path('cdlanding/', views.cdlanding, name='cdlanding'),
    path('cdabout/', views.cdabout, name='cdabout'),
    path('cdpurchase/', views.cdpurchase, name='cdpurchase'),
    path('purchase_cd/<str:pr_id>/', views.purchase_cd, name='purchase_cd'),
    path('cdppmp/', views.cdppmp, name='cdppmp'),
    path('cdresolution/', views.cdresolution, name='cdresolution'),
    path('preqform_cd/<str:pr_id>/', views.preqform_cd, name='preqform_cd'),
    path('purchase/<str:pr_id>/', views.purchase, name='purchase'),
    path('resolution/', views.resolution, name='resolution'),
    path('bac_dashboard/', views.bac_dashboard, name='bac_dashboard'),
    path('admin_home/', views.admin_home, name='admin_home'),
    path('adminabout/', views.adminabout, name='adminabout'),
    path('user/', views.user, name='user'),
    path('add_new_item/', add_new_item, name='add_new_item'),
    path('update_item/<str:id>/', views.update_item, name='update_item'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('handle_uploaded_file/', views.handle_uploaded_file, name='handle_uploaded_file'),
    path('delete_item/<int:id>/', delete_item, name='delete_item'),
    path('delete_category/<str:Category>/', delete_category, name='delete_category'),
    path('delete_user/<str:username>/', views.delete_user, name='delete_user'), 
    path('bohome/', views.bohome, name='bohome'),
    path('boabout/', views.boabout, name='boabout'),
    path('cdpurchase_approval/<str:pr_id>/', views.cdpurchase_approval, name='cdpurchase_approval'),
    path('bac_home/', views.bac_home, name='bac_home'),
    path('cdppmp_approval/<str:pr_id>/', views.cdppmp_approval, name='cdppmp_approval'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('update/<int:id>/', views.update, name='update'),
    path('ppmp/', views.ppmp, name='ppmp'),
    path('myppmp/', views.myppmp, name='myppmp'),
    path('purchase/', views.purchase, name='purchase'),
    path('approved_ppmp/', views.approved_ppmp, name='approved_ppmp'),
    path('user_add_new_item/', user_add_new_item, name='user_add_new_item'),
    path('budget-landing/', budget_landing, name='budget-landing'),
    path('purchasetracker/', views.purchasetracker, name='purchasetracker'),
    path('preqform_bo/<str:pr_id>/', views.preqform_bo, name='preqform_bo'),
    path('bac_request/', views.bac_request, name='bac_request'),
    path('bac_ppmp/<str:pr_id>/',views.bac_ppmp, name='bac_ppmp'),
    path('ppmpform/<int:year>/<str:pr_id>/', ppmpform, name='ppmpform'),
    path('bac_purchaserequest/<str:pr_id>/', views.bac_purchaserequest, name='bac_purchaserequest'),
    path('boppmp/<str:pr_id>/', views.boppmp, name='boppmp'),
    path('approve/', views.approve_user, name='approve_user'),
    path('new_ppmp/', views.new_ppmp, name='new_ppmp'),
     
]