from django.urls import path
from . import views 

urlpatterns = [
   path('',views.homepage, name='homepage'),
   path('main/',views.main, name='main'),
   path('login/',views.login, name='login'),
   path('register/',views.register, name='register'),
   path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),
   path('logout_user/',views.logout_user, name='logout_user'),
   path('requester/',views.requester, name='requester'),
   path('transaction_history/', views.transaction_history, name='transaction_history'),
   path('reset-password/', views.handle_reset_request, name='handle_reset_request'),
   path('verify-code/', views.verify_code, name='verify_code'),
   path('notif/',views.notification, name='notification'),
   path('tracker/',views.tracker, name='tracker'),
   path('about/',views.about, name='about'),
   path('history/',views.history, name='history'),
   path('profile/',views.profile, name='profile'),
   path('pro_file/',views.pro_file, name='pro_file'),
   path('profile_html/', views.profile_html, name='profile_html'),
   path('notif/', views.notification_html, name='notification_html'),
   path('about_cash/',views.about_cash, name='about_cash'),
   path('cash_disbursement/',views.cash_disbursement, name='cash_disbursement'),
   path('home_cash/',views.home_cash, name='home_cash'),
   path('purchase_request_cash/',views.prequest, name='prequest'),
   path('form',views.form, name='form'),
   path('reward_cash/',views.reward_cash, name='reward_cash'),
   path('BAC_about/',views.about_bac, name='about_bac'),
   path('BAC_home/',views.home_bac, name='home_bac'),
   path('BAC_purchase_request/',views.purchase_bac, name='purchase_bac'),
   path('campus_director/requester/', views.campus_director_requester,name='campusD_requester'),
   path('campus_director/notification/', views.campus_director_notification,name='campusD_notification'),
   path('campus_director/resolution/', views.campus_director_resolution,name='campusD_resolution'),
   path('campus_director/historycd/', views.campus_director_historycd,name='campusD_historycd'),
   path('campus_director/about/', views.campus_director_about,name='campusD_about'),
   path('supply_office/home/', views.supply_office_home,name='supply_office_home'),
   path('supply_office/notification/', views.supply_office_notification,name='supply_office_notification'),
   path('supply_office/history/', views.supply_office_history,name='supply_office_history'),
   path('supply_office/about/', views.supply_office_about,name='supply_office_about'),
   path('supply_office/inventory/', views.supply_office_inventory,name='supply_office_inventory'),
   path('notice_of_reward/',views.notice_of_reward, name='notice_of_reward'),  
   path('systemadmin/sahomepage/', views.sahomepage,name='sahomepage'),
]