# Generated by Django 4.1.13 on 2024-01-15 06:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='bup_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkout',
            name='bup_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='appr_ppmp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('item_brand_description', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('jan', models.IntegerField(default=0)),
                ('feb', models.IntegerField(default=0)),
                ('mar', models.IntegerField(default=0)),
                ('apr', models.IntegerField(default=0)),
                ('may', models.IntegerField(default=0)),
                ('jun', models.IntegerField(default=0)),
                ('jul', models.IntegerField(default=0)),
                ('aug', models.IntegerField(default=0)),
                ('sep', models.IntegerField(default=0)),
                ('oct', models.IntegerField(default=0)),
                ('nov', models.IntegerField(default=0)),
                ('dec', models.IntegerField(default=0)),
                ('estimate_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
