# Generated by Django 4.1.11 on 2023-12-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_id', models.CharField(max_length=100, unique=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[('approve', 'approve'), ('disapprove', 'disapprove')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='checkout',
            name='status_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
