# Generated by Django 3.0.5 on 2024-11-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pr_identifier',
            unique_together={('user', 'submission_date')},
        ),
    ]
