# Generated by Django 4.1.12 on 2023-11-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('submission_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateField()),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
