# Generated by Django 4.1.11 on 2024-01-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='cd_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkout',
            name='cd_disapprove',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkout',
            name='cd_seen',
            field=models.BooleanField(default=False),
        ),
    ]
