# Generated by Django 5.0 on 2024-01-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
            ],
        ),
        migrations.DeleteModel(
            name='AttachedFile',
        ),
        migrations.AddField(
            model_name='checkoutitems',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
