# Generated by Django 4.1.11 on 2023-12-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular User'), ('bac', 'BAC Secretariat'), ('campusd', 'Campus Director'), ('budget', 'Budget Officer'), ('admin', 'Admin')], max_length=10),
        ),
    ]
