# Generated by Django 4.1.11 on 2023-11-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='pr_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
