# Generated by Django 5.0 on 2024-01-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_attachment_delete_attachedfile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
