# Generated by Django 4.1.11 on 2023-12-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_request_checkout_status_checkout_status_update_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='status',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='status_update_date',
        ),
        migrations.AddField(
            model_name='checkout',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkout',
            name='is_disapprove',
            field=models.BooleanField(default=False),
        ),
    ]
