# Generated by Django 3.0.5 on 2024-11-14 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_purchasetracker_tracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseTracker',
        ),
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
