# Generated by Django 4.1.11 on 2024-01-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_checkoutitems_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutitems',
            name='attachment',
        ),
        migrations.AddField(
            model_name='checkout',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
