# Generated by Django 4.1.11 on 2024-01-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_checkout_cd_approve_checkout_cd_disapprove_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cd_disapprove',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='is_disapprove',
        ),
    ]
