# Generated by Django 3.0.5 on 2024-11-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20241122_1303'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pr_identifier',
            unique_together=set(),
        ),
    ]
