# Generated by Django 4.1.12 on 2024-01-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_checkout_comment_checkout_status_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
