# Generated by Django 4.1.12 on 2023-12-14 18:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
