# Generated by Django 4.1.11 on 2023-12-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_request_remove_checkout_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='is_approve',
            field=models.BooleanField(default=True),
        ),
    ]
