# Generated by Django 4.1.11 on 2023-10-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_campusdirectorhistorycd'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyOfficeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
