# Generated by Django 3.0.5 on 2024-11-22 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20241122_1309'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pr_identifier',
            unique_together={('user',)},
        ),
        migrations.RemoveField(
            model_name='pr_identifier',
            name='pr_id',
        ),
    ]
