# Generated by Django 4.1.11 on 2024-01-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_checkout_cd_disapprove_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='cd_approve',
            new_name='is_disapprove',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='cd_seen',
        ),
    ]
