# Generated by Django 3.0.5 on 2024-11-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20241122_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr_identifier',
            name='pr_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='pr_identifier',
            unique_together=set(),
        ),
    ]
