# Generated by Django 4.1.11 on 2023-12-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type'),
        ('accounts', '0004_item_total_cost'),
    ]

    operations = [
    ]
