# Generated by Django 4.1.11 on 2024-01-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_cd_approve_checkout_is_disapprove_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='cd_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkout',
            name='cd_disapprove',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkout',
            name='cd_seen',
            field=models.BooleanField(default=False),
        ),
    ]
