# Generated by Django 4.1.12 on 2023-12-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_item_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutitems',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
