# Generated by Django 3.0.5 on 2024-11-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20241122_1311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pr_identifier',
            unique_together={('user',)},
        ),
    ]
