# Generated by Django 4.1.11 on 2023-12-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_item_total_cost'),
        ('accounts', '0005_purchaserequestform_approved_and_more'),
    ]

    operations = [
    ]
