# Generated by Django 4.1.12 on 2024-01-11 19:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_item_apr_item_aug_item_dec_item_feb_item_jan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='estimate_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='mode_of_procurement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
