# Generated by Django 4.1.11 on 2023-12-15 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20231214_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='is_disapprove',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_cost',
        ),
    ]
