# Generated by Django 4.1.11 on 2023-12-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_checkout_is_disapprove_remove_item_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
