# Generated by Django 4.1.11 on 2023-12-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_checkout_is_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
