# Generated by Django 4.1.11 on 2023-12-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_checkout_is_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='is_seen',
            new_name='is_disapprove',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='is_approve',
            field=models.BooleanField(default=True),
        ),
    ]
