# Generated by Django 4.1.11 on 2023-12-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_is_seen_checkout_is_disapprove_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
