# Generated by Django 4.1.11 on 2023-12-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_checkout_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
