# Generated by Django 4.1.11 on 2024-01-05 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_checkout_is_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pr_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
