"""
Django settings for Supply_system project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$0$us08g%r@266))x3tyr5_hg0c1&k6u9ak#2zaj=(!!i-d^r+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['172.28.52.158','172.28.20.119', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.template',
    'accounts',
    'djongo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Supply_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Supply_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# defaultdb

# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'inventorydb',
#         'HOST': 'localhost',
#         'PORT': 27017,


#     }
# }

# jelyn database
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'inventory',
#         'HOST': 'localhost',
#         'PORT': 27017,
#     }
# }

# #Danica database
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'danicadb',
#         'CLIENT': {
#             'host': 'mongodb://localhost:27017/',
#         },
#     },
# }


# jhake database
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'inventory',
        'HOST': 'localhost',
        'PORT': 27017,
    },
}



# # jelyn database
# DATABASES = {
# 'default': {
#       'ENGINE': 'djongo',
#       'NAME':  'mydatabase',  
#       'USERNAME': 'lalyang',
#       'PASSWORD': 'lalyang123',
#       'HOST': 'localhost',
#       'PORT': 27017,
#       }
# # }
# jelyn database
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'inventory',
#         'HOST': 'localhost',
#         'PORT': 27017,


#    }
# }

# # jelyn database
# DATABASES = {
# 'default': {
#       'ENGINE': 'djongo',
#       'NAME':  'mydatabase',  
#       'USERNAME': 'lalyang',
#       'PASSWORD': 'lalyang123',
#       'HOST': 'localhost',
#       'PORT': 27017,
#       }
# }
# # =======
#  'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'mydatabase',   # Use the same database name as specified when creating the MongoDB user
#         'USER': 'ralphii',   # MongoDB username
#         'PASSWORD': 'ralph123',   # MongoDB password
#         'HOST': 'localhost',    # MongoDB host (can be a different host if MongoDB is not on the same server)
#         'PORT': 27017,          # MongoDB port (default is 27017)
#  }
# 


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/images/'

import os

static_dir = os.path.join(BASE_DIR, "static")

# Check if the directory exists, and create it if not
if not os.path.exists(static_dir):
    os.makedirs(static_dir)

static_dir = os.path.join(BASE_DIR, "static")

# Check if the directory exists, and create it if not
if not os.path.exists(static_dir):
    os.makedirs(static_dir)


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # SMTP server for Gmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'rlphtzn@gmail.com'  # Your Gmail email address
EMAIL_HOST_PASSWORD = 'ofaxjigazohzueet'  # Your Gmail password or app-specific password
